Modificacion(crud)
iaw-2022/ngeoffroy-laravel pull request #3
Opened 2022-05-18 23:27 UTC by ngeoffroy

Hola Fer como va. Te dejo el CRUD funcionando con administración de archivos para la subida de imágenes a google drive.
El usuario es el mismo que antes:  prueba@web.com pass: 123123123. 

Estoy al tanto por cualquier novedad!

Nicolas.

2022-05-31 16:37 UTC, hfmartinez85 requested changes
Hola Nico,

Te dejé algunos issues con errores que me surgieron probando la aplicación. Cuando los corrijas, haceme un nuevo pull request y verifico nuevamente.

Saludos,
Fernando

2022-06-06 02:47 UTC, ngeoffroy commented
> Hola Nico,
> 
> Te dejé algunos issues con errores que me surgieron probando la aplicación. Cuando los corrijas, haceme un nuevo pull request y verifico nuevamente.
> 
> Saludos, Fernando

¡Hola Fer! Perdón la demora, tuve unos inconvenientes al reinstalar todo por un tema de formateo. Ahí corregí los puntos que me marcaste y algunos detalles más. Te dejo de nuevo el link por las dudas: http://app-abs.herokuapp.com/ y la cuenta es la misma: prueba@web.com / 123123123
Cualquier cosa estoy al tanto.

Nicolas.

2022-06-16 19:15 UTC, hfmartinez85 approved these changes

2022-06-16 22:44 UTC, merged

2022-06-17 00:40 UTC, ngeoffroy commented
Hola Fer. Te dejo el link a la defensa del proyecto: https://www.youtube.com/watch?v=FmiRyYg-clQ
@hfmartinez85 

Cualquier cosa estoy al tanto.